apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
  namespace: pg-spring
data:
  init.sql: |
    #!/bin/bash
    set -e
    
    psql -U postgres -c "CREATE DATABASE IF NOT EXISTS market1;"